apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fi9cs3fqg-java-quarkus
  janus-idp.io/tekton: fi9cs3fqg-java-quarkus
  backstage.io/kubernetes-id: fi9cs3fqg-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fi9cs3fqg-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
